package pokemons;

public enum Nature {

	ADAMANT, BASHFUL, BOLD, BRAVE, CALM, CAREFUL, DOCILE, GENTLE, HASTY, 
    HARDY, IMPISH, JOLLY, LAX, LONELY, MILD, MODEST, NAIVE, NAUGHTY, 
    QUIET, QUIRKY, RASH, RELAXED, SASSY, SERIOUS, TIMID, WILD
	
}


